---
- name: Install Postgresql
  become: true
  ansible.builtin.apt:
    pkg:
    - postgresql
- name: Check if postgres is initialized
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register:
    postgres_data
- name: Start and enable postgres
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
- name: Create concourse Postgresql user if it doesn't exist
  ansible.builtin.shell: >
    psql postgres -tXAc "SELECT 1 FROM pg_roles WHERE rolname='{{concourse_postgres_user}}'" | grep -q 1 || createuser {{concourse_postgres_user}}
  become: true
  become_user: postgres
- name: Create atc Postgresql database if it doesn't exist
  ansible.builtin.shell: >
    psql postgres -tXAc "SELECT 1 FROM pg_database WHERE datname='{{concourse_postgres_db}}'" | grep -q 1 || createdb --owner={{concourse_postgres_user}} {{concourse_postgres_db}}
  become: true
  become_user: postgres
