---
- hosts: gitea
  roles:
  - { role: ../../../ansible/roles/bootstrap }
  - { role: ../../../ansible/community-roles/nginxinc.nginx }
  - gitea-postgres
  - gitea
- hosts: gitea
  vars:
    gitea_theme_default: arc-green
    gitea_db_type: postgres
    gitea_db_host: /run/postgresql/
    gitea_db_user: gitea
    gitea_db_name: gitea
    gitea_ssh_port: 22
    gitea_start_ssh: false
    gitea_shell: /usr/bin/bash
  roles:
  - { role: ../../../ansible/community-roles/thomas-maurice.gitea}