---
- hosts: proxmox
  roles:
  - role: ../../../ansible/roles/restic
  - role: ../../../ansible/roles/restic-repository
  - role: proxmox
    # vars:
      # job_end_cmd: "source /etc/restic/backup"
